version: "3.8"

services:
    nginx:
        image: nginx:latest
        network_mode: host
        volumes:
            - /share/CACHEDEV1_DATA/Container/Docker/Nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - /share/CACHEDEV1_DATA/Container/Docker/Nginx/proxy_params:/etc/nginx/proxy_params:ro
            - /share/CACHEDEV1_DATA/Container/Docker/Nginx/ssl/certs/local.network.crt:/etc/ssl/certs/local.network.crt:ro
            - /share/CACHEDEV1_DATA/Container/Docker/Nginx/ssl/private/local.network.key:/etc/ssl/private/local.network.key:ro
            # - ./html:/usr/share/nginx/html:ro
            # - ./logs:/var/log/nginx
        restart: unless-stopped
